services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1884:1883"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - "3123:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8066:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret

  mongo:
    image: mongo
    ports:
      - "27107:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7478:7474"
      - "7369:7687"
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  data_generator:
    build:
      context: .
    depends_on:
      - mqtt
      - mysql
      - mongo
      - neo4j
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    entrypoint: >
      /bin/sh -c "
      while ! nc -z mysql 3306;
      do
        echo 'Waiting for MySQL...';
        sleep 2;
      done;
      while ! nc -z mongo 27017;
      do
        echo 'Waiting for MongoDB...';
        sleep 2;
      done;
      while ! nc -z neo4j 7687;
      do
        echo 'Waiting for Neo4j...';
        sleep 2;
      done;
      while ! nc -z mqtt 1883;
      do
        echo 'Waiting for MQTT broker...';
        sleep 2;
      done;
      python /app/data_generator.py
      "
